builds: []
variables:
- name: Image
  value: builder-dev.acornsoft.io/apps/gin-gonic:latest
- name: Replicas
  value: 1
- name: RequestCpu
  value: 100m
- name: RequestMemory
  value: 100Mi
- name: LimitCpu
  value: 100m
- name: LimitMemory
  value: 100Mi
addons: []
